### ISSUE TITLE
分析后报错：Illegal instruction: 4   当前目录也没有生成DrafterStage文件夹

### ISSUE THREAD

**Issue by zeuskim** [L-Zephyr/Drafter#11]
你好，分析后报错：Illegal instruction: 4   当前目录也没有生成DrafterStage文件夹

**Comment by L-Zephyr** [comment]
@zeuskim 你好，从报错信息来看是文件编码的问题，请问matrix3d.h这个文件的编码是什么？文件编码最好使用UTF-8

**Comment by zeuskim** [comment]
> @zeuskim 你好，从报错信息来看是文件编码的问题，请问matrix3d.h这个文件的编码是什么？文件编码最好使用UTF-8

我把有问题 的文件都修改了，没有报Fail To Read File错误，但仍然报Illegal instruction: 4

**Comment by L-Zephyr** [comment]
> > @zeuskim 你好，从报错信息来看是文件编码的问题，请问matrix3d.h这个文件的编码是什么？文件编码最好使用UTF-8
> 
> 我把有问题 的文件都修改了，没有报Fail To Read File错误，但仍然报Illegal instruction: 4

emmm....这就有点奇怪了，你的系统版本和Xcode的版本是多少？

**Comment by L-Zephyr** [comment]
> > > > @zeuskim 你好，从报错信息来看是文件编码的问题，请问matrix3d.h这个文件的编码是什么？文件编码最好使用UTF-8
> > > 
> > > 
> > > 我把有问题 的文件都修改了，没有报Fail To Read File错误，但仍然报Illegal instruction: 4
> > 
> > 
> > emmm....这就有点奇怪了，你的系统版本和Xcode的版本是多少？
> 
> 系统版本 10.13.6 (17G65) xcode版本： 10.0 (10A255)

我这边无法复现这个问题，你试试看这个`curl "https://raw.githubusercontent.com/L-Zephyr/static_resource/master/Drafter/install.sh" | /bin/sh`，这个脚本会直接安装一份我编译好的文件

**Comment by zeuskim** [comment]
> > > > > @zeuskim 你好，从报错信息来看是文件编码的问题，请问matrix3d.h这个文件的编码是什么？文件编码最好使用UTF-8
> > > > 
> > > > 
> > > > 我把有问题 的文件都修改了，没有报Fail To Read File错误，但仍然报Illegal instruction: 4
> > > 
> > > 
> > > emmm....这就有点奇怪了，你的系统版本和Xcode的版本是多少？
> > 
> > 
> > 系统版本 10.13.6 (17G65) xcode版本： 10.0 (10A255)
> 
> 我这边无法复现这个问题，你试试看这个`curl "https://raw.githubusercontent.com/L-Zephyr/static_resource/master/Drafter/install.sh" | /bin/sh`，这个脚本会直接安装一份我编译好的文件

你好，用这个运行， 报错：
Fatal error: String index is out of bounds
Illegal instruction: 4

**Comment by L-Zephyr** [comment]
@zeuskim 这应该是词法分析的bug，当文件的最后一个字符是`-`时会触发这个case导致越界，之前因为Xcode会自动在每个文件的结尾加上一个换行符所以一直没有发现，已经修复，请重新执行一次安装脚本

**Comment by zeuskim** [comment]
> @zeuskim 这应该是词法分析的bug，当文件的最后一个字符是`-`时会触发这个case导致越界，之前因为Xcode会自动在每个文件的结尾加上一个换行符所以一直没有发现，已经修复，请重新执行一次安装脚本

你好，这边没有报之前的错误了，非常感谢！
