### ISSUE TITLE
运行报错：Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by Elliotsomething** [L-Zephyr/Drafter#12]
运行代码报错：
Script-BB046FB520B03E5400DD5546.sh: line 2: sourcery: command not found
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by L-Zephyr** [comment]
@Elliotsomething 这是一个Xcode脚本的报错，这个脚本会使用Sourcery来生成代码。我已经修改了脚本，避免在没有安装Sourcery的时候报错，更新一下就好了
