### ISSUE TITLE
运行“curl "https://raw.githubusercontent.com/L-Zephyr/Drafter/master/install.sh" | /bin/sh”报错

### ISSUE THREAD

**Issue by jashion** [L-Zephyr/Drafter#2]
error: argument 'targets' must precede argument 'dependencies'
    targets: [
    ^~~~~~~~~~
    dependencies: []
Can't parse Package.swift manifest file because it contains invalid format. Fix Package.swift file format and try again.
error: invalidManifestFormat

**Comment by L-Zephyr** [comment]
请用指令`swift package --version`确认一下SPM的版本是不是4.0

**Comment by superous123** [comment]
![image](https://user-images.githubusercontent.com/10149961/38593550-725c15ee-3d74-11e8-953c-11e0a2dd1616.png)

![image](https://user-images.githubusercontent.com/10149961/38593594-b0c90c1a-3d74-11e8-84c8-61952203383e.png)

**Comment by huangdaxiaEX** [comment]
@superous123 修改下源文件

**Comment by L-Zephyr** [comment]
@superous123  已经修复了，重新运行一下安装命令即可
