### ISSUE TITLE
/bin/sh: line 8: cd: .build/release: No such file or directory

### ISSUE THREAD

**Issue by superous123** [L-Zephyr/Drafter#3]
Apple Swift Package Manager - Swift 4.1.0 (swiftpm-14050)

![image](https://user-images.githubusercontent.com/10149961/38593610-c9e13704-3d74-11e8-9a45-64ca0c46285e.png)

**Comment by L-Zephyr** [comment]
Fixed, run `curl "https://raw.githubusercontent.com/L-Zephyr/Drafter/master/install.sh" | /bin/sh` again please
