### ISSUE TITLE
突发奇想，大神既然都研究到这一层了，能否做个 OC 转 JavaScript 的库，哈哈

### ISSUE THREAD

**Issue by xpsuper** [L-Zephyr/Drafter#6]

**Comment by L-Zephyr** [comment]
谢谢。OC转JS没什么实际的应用场景啊

**Comment by xpsuper** [comment]
其实是有用的，16年年底滴滴提出的 DynamicCocoa 的思路大神可以了解一下，其实就是
下发 OC 代码 ——> OC 转 JavaScript ——> JavaScriptCore ——> OC Native Runtime 
是不是可以不依靠前端，OC开发者自己就可以做很多事情了，呵呵
